services:
  nexrack-quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: nexrack-quarkus
    restart: always
    expose:
      - "8080"    # Exposed inside docker only to nginx
    networks:
      - nexrack-quarkus-network
      - nexrack-uptime-kuma-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - autoheal=true

  nexrack-db:
    image: postgres:latest
    container_name: nexrack-db
    ports:
      - "15432:5432"
    restart: always
    environment:
      - POSTGRES_USER=nexrack_admin
      - POSTGRES_PASSWORD=nexrack_admin_password
      - POSTGRES_DB=nexrack_db
    volumes:
      - ./docker/nexrack-core/postgresql/data:/var/lib/postgresql/data
    networks:
      - nexrack-quarkus-network
      - nexrack-pgadmin-network
    labels:
      - autoheal=true

  nexrack-pgadmin:
    image: dpage/pgadmin4
    container_name: nexrack-pgadmin
    expose:
      - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nexrack@admin.com
      PGADMIN_DEFAULT_PASSWORD: nexrack_admin_password
    depends_on:
      - nexrack-db
    networks:
      - nexrack-nginx-network
      - nexrack-pgadmin-network
    user: '$UID:$GID'
    volumes:
      - ./docker/nexrack-core/pgadmin-data/:/var/lib/pgadmin/
    labels:
      - autoheal=true

  nexrack-nginx:
    image: nginx:latest
    container_name: nexrack-nginx
    ports:
      - "8080:80"  # Exposed port to the host through 8888
    restart: always
    networks:
      - nexrack-nginx-network
      - nexrack-pgadmin-network
      - nexrack-quarkus-network
    volumes:
      - ./docker/nexrack-core/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - autoheal=true

  nexrack-autoheal:
    image: willfarrell/autoheal
    container_name: nexrack-autoheal
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow autoheal to monitor the Docker daemon
    networks:
      - nexrack-quarkus-network

networks:
  nexrack-nginx-network:
    driver: bridge
  nexrack-uptime-kuma-network:
    driver: bridge
  nexrack-quarkus-network:
    driver: bridge
  nexrack-pgadmin-network:
    driver: bridge